version: '3.7'

services:
  backend:
    image: product-search-app:latest
    environment:
      DEPLOYMENT: "dev"
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SSL: ${REDIS_SSL}
    expose:
      - "8888"
    ports:
      - "8888:8888"
